" Shared by vim and neovim -- ~/.config/nvim/init.vim only sources this file.
" Everything that genuinely differs between the two is guarded with has('nvim').

" Neovim does not look in ~/.vim, so send it there for colors/, syntax/, indent/,
" ftdetect/, after/ and pack/ rather than keeping a second copy of all of it.
if has('nvim')
  set runtimepath^=~/.vim
  set runtimepath+=~/.vim/after
  let &packpath = &runtimepath
endif

"""""""""""""""""""""""""""""""""""""""""""""""""""""
"Indentation
"""""""""""""""""""""""""""""""""""""""""""""""""""""
set noexpandtab
set shiftwidth=0
set tabstop=4
set softtabstop=4
set textwidth=0

" for work, disable python settings
let g:python_recommended_style = 0

set autoindent
filetype plugin indent on
syntax enable

set encoding=utf-8
set fileencodings=ucs-bom,utf-8,default,latin1

"things after case labels aren't indented
"so I can add braces in case statements
set cino=g0,:0,=0

" when joining lines with comments at front, remove comments
set formatoptions+=j

set nu

set splitright
set splitbelow

set showcmd

set nostartofline

set nofixeol

set sidescroll=1

let g:markdown_folding = 1
"""""""""""""""""""""""""""""""""""""""""""""""""""""
"Code Navigation
"""""""""""""""""""""""""""""""""""""""""""""""""""""
if has('termguicolors')
  set termguicolors
  if !has('nvim')
    " t_8f/t_8b must be spelled out because screen/xterm terminfo does not advertise
    " 24-bit color, and without them termguicolors emits nothing vim's :terminal can use.
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  endif
endif

" mate-terminal's Tango palette, so a :terminal buffer looks like the real terminal.
" Vim reads g:terminal_ansi_colors and neovim reads g:terminal_color_0..15; onedark
" only ever sets the neovim names, so without this vim falls back to its own
" fluorescent defaults (#E0E000 for yellow).
let s:tango_normal = ['#2E3436', '#CC0000', '#4E9A06', '#C4A000', '#3465A4', '#75507B', '#06989A', '#D3D7CF']
let s:tango_bright = ['#555753', '#EF2929', '#8AE234', '#FCE94F', '#729FCF', '#AD7FA8', '#34E2E2', '#EEEEEC']
if has('nvim')
  function! s:ApplyTerminalColors()
    let l:palette = s:tango_normal + s:tango_bright
    for i in range(16)
      let g:terminal_color_{i} = l:palette[i]
    endfor
  endfunction
else
  " Vim brightens bold ANSI colors where mate-terminal does not, so the bright half
  " repeats the normal half. Otherwise every \e[1;3Xm came out glowing.
  function! s:ApplyTerminalColors()
    let g:terminal_ansi_colors = s:tango_normal + s:tango_normal
  endfunction
endif

set completeopt+=longest
set showmatch
set incsearch
set ruler
set tagcase=smart
set ignorecase
set smartcase
set lazyredraw
set hlsearch

" Disable mouse or it keeps clicking accidentally in terminal
set mouse=

" Match location/quickfix list error format
"  for easy use with :lgetbuffer
set errorformat+=%f\|%l\ col\ %c\|%m

set foldlevelstart=99
set foldmethod=indent

set nobackup
set nowritebackup
set undofile
set noswapfile

" mkdir because vim silently writes no undo file at all when 'undodir' does not
" exist, and neovim's undo format is not interchangeable with vim's so the two
" need separate directories.
" expand() because vim does not expand a leading ~ in 'undodir' and then silently
" writes no undo file at all.
let s:vim_dir = expand(has('win32') ? '~/dot-files/vim' : '~/.vim')
let s:undo_dir = s:vim_dir . (has('nvim') ? '/undo-nvim' : '/undo')
call mkdir(s:undo_dir, 'p')
let &undodir = s:undo_dir . '//'
let &directory = s:vim_dir . '/swap//'

if has("gui_running")
  set lines=30 columns=120
  " Neovim has no 'guioptions'.
  if exists('+guioptions')
    set guioptions=c
  endif
endif

set history=500
set nrformats=bin,hex,alpha
set backspace=indent,eol,start " be able to backspace over these chars

set autoread

set listchars=tab:»·,trail:·,nbsp:·
set list
let s:list_tracker = &list

set wildmode=list:longest,full " tab complete to longest match, second tab lists all matches
set wildignorecase " ignore case when completing file and dir names
set wildignore+=*.o
set wildignore+=*.r43
set wildignore+=*.pbi*
set wildignore+=*.lst

set virtualedit=block " allow visual mode block editing to extend past EOL

" search for tag file relative to current working directory rather than
" current file's directory
set cpoptions+=d

" Called on ColorScheme rather than from inside 'statusline', which ran this :hi
" on every single redraw.
function! s:StatusLineColor()
  hi! User9 term=bold cterm=bold ctermfg=red guifg=red
endfunction
set laststatus=2    " always display statusline
set statusline=%<%F " file name and path
set statusline+=\ %9*%m%*%r%* " modified in red (User9), read-only flags
set statusline+=\ %y  " filetype according to vim
set statusline+=\ %n  " buffer number
set statusline+=\ [%{&ff}] " show detected line endings for file
set statusline+=%=
set statusline+=\ [0x\%02.6B] " hex value under cursor showing three bytes for unicode
set statusline+=\ [%{&encoding}] " encoding for file
set statusline+=\ [%2.10(%l:%c%V%)\ \/\ %L] " line:column / total lines

if executable('rg') "name on windows
  set grepprg=rg\ --no-messages\ --vimgrep\ --max-filesize\ 5M\ --type-add\ zig:\*.zig
  set grepformat=%f:%l:%c:%m,%f:%l:%m
endif

if has("patch-8.1.0360")
  set diffopt=internal,filler,indent-heuristic,algorithm:histogram
  set diffexpr=""
elseif executable('diff')
  set diffexpr=MyDiff()
  function! MyDiff()
    let opt = ""
    if &diffopt =~ "icase"
      let opt = opt . "-i "
    endif
    if &diffopt =~ "iwhite"
      let opt = opt . "-b "
    endif
      silent execute "!diff --text --new-file --minimal " . opt . v:fname_in . " " . v:fname_new .
        \  " > " . v:fname_out
  endfunction
else
  set diffopt=filler
  set diffexpr=""
endif

"""""""""""""""""""""""""""""""""""""""""""""""""""""
"Terminal Settings
"""""""""""""""""""""""""""""""""""""""""""""""""""""
let s:local_terminal_name = 'LOCAL'
let s:global_terminal_name = 'GLOBAL'
" Lists, not strings, so neither editor puts an extra shell in the way.
let s:windows_default_term = ['C:\Program Files\Git\bin\bash.exe']
let s:linux_default_term = ['/usr/bin/env', 'bash']
"""""""""""""""""""""""""""""""""""""""""""""""""""""
"Key maps
"""""""""""""""""""""""""""""""""""""""""""""""""""""
"unmap windows visual mode cut to clipboard. Use for decrementing lists
silent! vunmap <c-x>
set timeout timeoutlen=1000 ttimeoutlen=200
inoremap jk <esc>
vnoremap s( c()<ESC>P
vnoremap s\| c\|\|<ESC>P
vnoremap s{ c{}<ESC>P
vnoremap s[ c[]<ESC>P
vnoremap s" c""<ESC>P
vnoremap s` c``<ESC>P
vnoremap s' c''<ESC>P
vnoremap s< c<><ESC>P
vnoremap s_ c__<ESC>P
vnoremap s* c**<ESC>P
nnoremap ds( %x<c-o>x
nnoremap ds{ %x<c-o>x
nnoremap ds" %x<c-o>x
nnoremap ds` %x<c-o>x
nnoremap ds' %x<c-o>x
nnoremap dif viwl%d
nnoremap yif viwl%y
vnoremap <Bslash>bs c{<CR>}<ESC>P=i{
vnoremap s<SPACE> di<SPACE><SPACE><ESC>P
nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk
nnoremap gj j
nnoremap gk k
vnoremap gj j
vnoremap gk k
nnoremap <c-j> :lnext<CR>z.
nnoremap <c-k> :lprevious<CR>z.
nnoremap J :cnext<CR>z.
nnoremap K :cprevious<CR>z.
nnoremap <Bslash>j :lnewer<CR><CR>
nnoremap <Bslash>k :lolder<CR><CR>
nnoremap <Bslash>h :nohl<CR>
nnoremap <SPACE> za
nnoremap <Bslash>. 10<c-w>>
nnoremap <Bslash>, 10<c-w><
nnoremap <Bslash>- 10<c-w>-
nnoremap <Bslash>= 10<c-w>+
nnoremap <Bslash>l :LocationListToggle<CR>
nnoremap <Bslash>C :let &l:colorcolumn=virtcol('.')<CR>
nnoremap <Bslash>c :let &l:colorcolumn=""<CR>
vnoremap <Bslash>/ :Comment<CR>
vnoremap <Bslash>\ :Uncomment<CR>
nnoremap <Bslash>/ :Comment<CR>
nnoremap <Bslash>\ :Uncomment<CR>
" Terminal mode reaches the command line with <c-w> in vim, <c-\><c-n> in neovim.
let s:term_cmd = has('nvim') ? '<c-\><c-n>:' : '<c-w>:'

let s:toggle_commands = {
      \ 'n'   : 'VerticalSplitNoteToggle',
      \ 'gn'  : 'GlobalVerticalSplitNoteToggle',
      \ 't'   : 'TerminalToggle',
      \ 'vt'  : 'VerticalTerminalToggle',
      \ 'gt'  : 'GlobalTerminalToggle',
      \ 'gvt' : 'GlobalVerticalTerminalToggle',
      \ 'ct'  : 'ClaudeCodeTerminalToggle',
      \ }
for [s:key, s:command] in items(s:toggle_commands)
  execute 'nnoremap <c-Bslash>' . s:key . ' :' . s:command . '<CR>'
  execute 'tnoremap <c-Bslash>' . s:key . ' ' . s:term_cmd . s:command . '<CR>'
endfor

nnoremap <c-w>] yiw:vert stag! <c-r>"<CR>
nnoremap <c-w>g] yiw:vert stselect! <c-r>"<CR>
nnoremap <c-w>M <c-w>\|<c-w>_
vnoremap <c-w>M <c-w>\|<c-w>_
if has('nvim')
  " Trailing i goes back to terminal mode after the resize.
  tnoremap <c-w>M <c-\><c-n><c-w>\|<c-w>_i
else
  tnoremap <c-w>M <c-w>\|<c-w>_
endif
vnoremap <Bslash>= c<c-R>=<c-R>"<CR><ESC>
" yank inside visual selection, cursor returns to where it was, can specify any register
" from https://ddrscott.github.io/blog/2016/yank-without-jank/
vnoremap <expr> y "my\"" . v:register . "y`y"
vnoremap /  y/<c-R>"<CR>
" * key doesn't auto jump
" Also put the *'d text into the search history buffer by
"  re-inserting the text into the "/" register through pasting
nnoremap <silent> * :let @/=expand("<cword>")<CR>:set hls<CR>:%s///gn<CR>:normal /<c-r>/<CR>
vnoremap <silent> * y:let @/='\V'.substitute(@",'\\','\\\\','g')->substitute('\n', '\\n','g')->substitute('\r', '\\r','g')<CR>:set hls<CR>:%s///gn<CR>:normal /<c-r>/<CR>

"lgrep search hotkeys
command! -nargs=+ -complete=tag Lgrep lgrep -L <args>
nnoremap <Bslash>s "myiw:Lgrep "<c-R>m"<SPACE>
nnoremap <Bslash>S "myiw:lgrep "<c-R>m"<SPACE>
vnoremap <Bslash>s "my:Lgrep<SPACE>"<c-R>m"<SPACE>
nnoremap <Bslash>f :let @m=expand('<cfile>')<CR>:Find<SPACE><c-R>m
vnoremap <Bslash>f "my:Find<SPACE><c-R>m

execute 'tnoremap <c-g><c-t> ' . s:term_cmd . 'tabnext<CR>'
execute 'tnoremap <c-g>t     ' . s:term_cmd . 'tabprevious<CR>'
nnoremap <c-g><c-t> :tabnext<CR>
nnoremap <c-g>t     :tabprevious<CR>

" Command line history completion
cnoremap <c-j> <Down>
cnoremap <c-k> <Up>

vnoremap g] "my:tjump<SPACE><c-R>m
nnoremap g] :let @m=expand('<cword>')<CR>:tjump<SPACE><c-R>m

" GDB mappings
execute 'tnoremap <c-Bslash>R ' . s:term_cmd . 'RegisterTerminalBuffer<CR>'
nnoremap <Bslash>E :let @m=expand('<cexpr>')<CR>:Evaluate<SPACE><c-R>m
" join lines together by removing newlines (null bytes in register)
" also shrink excess spaces down to just one space, removing tabs
vnoremap <Bslash>E "my:let @m=substitute(@m,'\v\s+',' ','g')<CR>:let @m=substitute(strtrans(@m),'\^@',' ','g')<CR>:Evaluate<SPACE><c-R>m
"""""""""""""""""""""""""""""""""""""""""""""""""""""
"Functions
"""""""""""""""""""""""""""""""""""""""""""""""""""""
function MyTabLine()
  let s = ''
  for i in range(tabpagenr('$'))
    " select the highlighting
    if i + 1 == tabpagenr()
      let s .= '%#TabLineSel#'
    else
      let s .= '%#TabLine#'
    endif

    " set the tab page number (for mouse clicks)
    let s .= '%' . (i + 1) . 'T'

    " the label is made by MyTabLabel()
    let s .= '   %{MyTabLabel(' . (i + 1) . ')}   '
  endfor

  " after the last tab fill with TabLineFill and reset tab page nr
  let s .= '%#TabLineFill#%T'

  " right-align the label to close the current tab page
  if tabpagenr('$') > 1
    let s .= '%=%#TabLine#%999Xclose'
  endif

  return s
endfunction

function! MyTabLabel(n)
  return getcwd(tabpagewinnr(a:n), a:n)
endfunction

set tabline=%!MyTabLine()
"""""""""""""""""""""""""""""""""""""""""""""""""""""
if !exists('s:terminal_counter')
  let s:terminal_counter = 0
endif
function! TermStart(term_name)
  let l:cmd = has('win32') ? s:windows_default_term : s:linux_default_term
  let l:name = a:term_name . s:terminal_counter
  if has('nvim')
    " termopen() takes over the current buffer the way term_start()'s curwin did.
    " There is no term_name equivalent, so the buffer gets renamed afterwards.
    if has('nvim-0.11')
      call jobstart(l:cmd, {'term': v:true})
    else
      call termopen(l:cmd)
    endif
    setlocal scrollback=100000
    execute 'keepalt file' fnameescape(l:name)
  else
    call term_start(l:cmd, {'curwin': 1, 'term_name': l:name, 'norestore': 1})
    setlocal termwinscroll=100000
  endif
  let s:terminal_counter += 1
  setlocal nonumber
endfunction

" Vim addresses a running terminal by buffer number, neovim by the job id it
" stores on that buffer.
function! s:TermSendKeys(bufnr, keys)
  if !has('nvim')
    call term_sendkeys(a:bufnr, a:keys)
    return
  endif
  let l:job = getbufvar(a:bufnr, 'terminal_job_id', 0)
  if l:job == 0
    echoerr 'buffer ' . a:bufnr . ' is not a terminal'
    return
  endif
  call chansend(l:job, a:keys)
endfunction
"""""""""""""""""""""""""""""""""""""""""""""""""""""
function! s:SetupPlugins()
"called on autocommand that is triggered after
"plugins are setup (post vimrc sourcing)
  if exists(":AsyncRun")
    let s:async_run_mod = "AsyncRun "
  else
    let s:async_run_mod = "!"
  endif
endfunction
if v:vim_did_enter
  call s:SetupPlugins()
endif
"""""""""""""""""""""""""""""""""""""""""""""""""""""
command! -nargs=? -complete=dir Ctags call s:EasyCtags(<q-args>)
function! s:EasyCtags(...)
  let rel_arg = "y"
  if has('win32')
    let rel_arg = "always"
  endif
  if a:0 > 0 "&& (match(a:000, '^.\+$') == 0)
    let l:dir_and_extra_parms = ""
    for item in a:000
    let l:dir_and_extra_parms .= item
    endfor
  else
    let l:dir_and_extra_parms = getcwd(win_getid())
  endif
  let langMapChange = ['c', 'cpp', 'msp', 'asm']
  let commonOptions =  "--tag-relative=".rel_arg." --pattern-length-limit=0 --excmd=number --fields=+{signature}+{inherits}"
  if index(langMapChange, &ft) >= 0
    let executableString = s:async_run_mod . 'ctags -R --languages=C,C++ '.commonOptions.' '.l:dir_and_extra_parms
    "." && ctags -Ra ".commonOptions." --langmap=Asm:+.s43.S43.h.inc ".l:dir_and_extra_parms
  else
    let executableString = s:async_run_mod . 'ctags -R '.commonOptions.' '.l:dir_and_extra_parms
  endif
  echo executableString
  execute(executableString)
endfunction
"""""""""""""""""""""""""""""""""""""""""""""""""""""
command! LocationListToggle call s:LocationListToggle()
function! s:LocationListToggle()
  if exists("w:location_list_orig") "we are in location list
    execute w:location_list_orig."wincmd w"
    unlet w:location_list_winnr
    lclose
  elseif exists("w:location_list_winnr") "we are in original window
    unlet w:location_list_winnr
    lclose
  else
    let t:temp1 = winnr() "original window number
    lopen 15
    let t:temp2 = winnr() "location list window number tied to previous window
    let w:location_list_orig = t:temp1
    execute w:location_list_orig."wincmd w"
    let w:location_list_winnr = t:temp2
    execute w:location_list_winnr."wincmd w"
  endif
endfunction
"""""""""""""""""""""""""""""""""""""""""""""""""""""
let s:comment_characters = {
      \"c"      : "//",
      \"cpp"    : "//",
      \"cs"     : "//",
      \"zig"    : "//",
      \"asm"    : "//",
      \"javascript"    : "//",
      \"javascriptreact"    : "//",
      \"msp"    : ";",
      \"sh"     : "#",
      \"pov"    : "#",
      \"nim"    : "#",
      \"make"   : "#",
      \"vim"    : "\"",
      \"gdb"    : "#",
      \"dosbatch": "REM ",
      \"python" : "# ",
      \"vhdl" : "--",
      \"tex" : "%",
      \}
command! -range Comment <line1>,<line2>call s:Comment()
function! s:Comment()
  if (has_key(s:comment_characters,&filetype))
    let comment_at_caret = "s:\\v(^\\s*)(\\S):\\1".s:comment_characters[&filetype]."\\2:e"
    let comment_at_0 = "s:\\v(^.*$):".s:comment_characters[&filetype]."\\1:e"
    execute comment_at_0
  else
    echo "Unknown comment character for filetype, see vimrc"
  endif
endfunction
command! -range Uncomment <line1>,<line2>call s:Uncomment()
function! s:Uncomment()
  if (has_key(s:comment_characters,&filetype))
    execute "s:\\v(^\\s*)".s:comment_characters[&filetype].":\\1:e"
  else
    echo "Unknown comment character for filetype, see vimrc"
  endif
endfunction
"""""""""""""""""""""""""""""""""""""""""""""""""""""
function! s:LowerFirst(text)
  return tolower(a:text[0]) . a:text[1:]
endfunction
function! s:UpperFirst(text)
  return toupper(a:text[0]) . a:text[1:]
endfunction
" -range=% because a bare :S used to change only the current line, which looks
" exactly like the command not working.
command! -range=% -complete=tag -nargs=+ S call s:SearchAndReplaceKeepCase(<line1>, <line2>, <f-args>)
function! s:SearchAndReplaceKeepCase(first, last, word, replacement, ...)
  " This function takes camelCase or PascalCase search and replace string and also does replace on
  " camelCase version, PascalCase version, all lowercase version, and UPPERCASE version
  " Optionally you can pass in modifiers to the standard substitution command like c for confirm

  " Example: S aThing anotherThing
  " aThing    anotherThing
  " AThing    AnotherThing
  " athing    anotherthing
  " ATHING    ANOTHERTHING
  "
  " qaThing   qaThing
  " qAThing   qAThing
  " qathing   qathing
  " qATHING   qATHING
  "
  " aThingq   aThingq
  " AThingq   AThingq
  " athingq   athingq
  " ATHINGq   ATHINGq
  "
  " qaThingq  qaThingq
  " qAThingq  qAThingq
  " qathingq  qathingq
  " qATHINGq  qATHINGq

  " camelCase first: for a single-word argument its pattern is identical to the
  " all-lowercase one, and camelCase is the more useful of the two results.
  let l:variants = [
        \ [s:LowerFirst(a:word), s:LowerFirst(a:replacement)],
        \ [s:UpperFirst(a:word), s:UpperFirst(a:replacement)],
        \ [tolower(a:word),      tolower(a:replacement)],
        \ [toupper(a:word),      toupper(a:replacement)],
        \ ]

  " Changing only capitalisation makes every variant an identity substitution, so
  " say so rather than reporting nothing at all.
  if empty(filter(copy(l:variants), 'v:val[0] !=# v:val[1]'))
    echohl WarningMsg
    echomsg 'S: no variant of ' . a:word . ' differs from ' . a:replacement . ', nothing to do'
    echohl None
    return
  endif

  " e so a variant that does not occur is not an error. No silent!, because that
  " hid genuine failures too.
  let l:flags = 'ge' . get(a:, 1, '')
  for [l:from, l:to] in l:variants
    execute printf('%d,%ds;\C\<%s\>;%s;%s', a:first, a:last,
          \ escape(l:from, '\;.*$^~[]'), escape(l:to, '\;&~'), l:flags)
  endfor
endfunction
"""""""""""""""""""""""""""""""""""""""""""""""""""""
command! VerticalSplitNoteToggle call s:VerticalSplitNoteToggle()
function! s:VerticalSplitNoteToggle()
  if exists("t:notes_win_number")
    if win_id2win(t:notes_win_number)
      execute win_id2win(t:notes_win_number)."close!"
    endif
    unlet t:notes_win_number
  else
    botright vsplit NOTES.md
    let t:notes_win_number = win_getid(winnr())
    vertical resize 85
  endif
endfunction
command! GlobalVerticalSplitNoteToggle call s:GlobalVerticalSplitNoteToggle()
function! s:GlobalVerticalSplitNoteToggle()
  if exists("t:global_notes_win_number")
    if win_id2win(t:global_notes_win_number)
      execute win_id2win(t:global_notes_win_number)."close!"
    endif
    unlet t:global_notes_win_number
  else
    botright vsplit ~/NOTES.md
    let t:global_notes_win_number = win_getid(winnr())
    vertical resize 85
  endif
endfunction
"""""""""""""""""""""""""""""""""""""""""""""""""""""
function! s:SimpleTerminalToggle(win_var, buf_var, scope, term_name, split_cmd, size)
  " The window variable is always tab-local -- each tab needs its own window onto
  " the terminal. It is the buffer variable going global that makes a global
  " terminal the same terminal in every tab.
  let l:win_var_name = 't:'.a:win_var
  let l:buf_var_name = a:scope == 'global' ? 'g:'.a:buf_var : 't:'.a:buf_var

  if exists(l:win_var_name)
    let l:win_id = {l:win_var_name}
    if win_id2win(l:win_id)
      execute win_id2win(l:win_id)."wincmd w"
      hide
    endif
    unlet {l:win_var_name}
  else
    execute a:split_cmd
    if a:size > 0
      if a:split_cmd =~# 'vnew'
        execute 'vertical resize '.a:size
      else
        execute 'resize '.a:size
      endif
    endif
    let {l:win_var_name} = win_getid(winnr())
    if exists(l:buf_var_name) && bufexists({l:buf_var_name})
      execute "buf ".{l:buf_var_name}
    else
      call TermStart(a:term_name)
      let {l:buf_var_name} = bufnr("%")
    endif
  endif
endfunction
"""""""""""""""""""""""""""""""""""""""""""""""""""""
command! TerminalToggle               call s:SimpleTerminalToggle('terminal_win_num', 'terminal_buf_num', 'local', s:local_terminal_name, 'botright new', 16)
command! VerticalTerminalToggle       call s:SimpleTerminalToggle('vertical_terminal_win_num', 'vertical_terminal_buf_num', 'local', s:local_terminal_name, 'botright vnew', 0)
command! GlobalTerminalToggle         call s:SimpleTerminalToggle('global_terminal_win_num', 'global_terminal_buf_num', 'global', s:global_terminal_name, 'botright new', 16)
command! GlobalVerticalTerminalToggle call s:SimpleTerminalToggle('global_vertical_terminal_win_num', 'global_vertical_terminal_buf_num', 'global', s:global_terminal_name, 'botright vnew', 0)
command! ClaudeCodeTerminalToggle     call s:SimpleTerminalToggle('claude_code_terminal_win_num', 'claude_code_terminal_buf_num', 'local', 'CLAUDE', 'botright vnew', 85)
"""""""""""""""""""""""""""""""""""""""""""""""""""""
command! -complete=file_in_path -nargs=1 Find call s:Find(<q-args>)
function! s:Find(...)
  if a:0 < 1
    return
  endif
  let temp = &grepformat
  set grepformat=%f
  let exeString = "silent grep --files --iglob ".a:1
  execute(exeString)
  execute('set grepformat='.temp)
endfunction
"""""""""""""""""""""""""""""""""""""""""""""""""""""
command! -nargs=0 RegisterTerminalBuffer let t:termBufNr = bufnr("%")
"""""""""""""""""""""""""""""""""""""""""""""""""""""
function! s:GetTermBufNr()
  let termBuf = get(t:,'termBufNr',-1)
  if termBuf < 0
    echoerr "RegisterTerminalBuffer first"
  endif
  return termBuf
endfunction

function! s:SendGDBLineCommand(termBuf, command, appendedText)
  let l:file = expand("%:.:")
  let l:line = line(".")
  let pos = l:file.':'.l:line
  call s:TermSendKeys(a:termBuf, a:command . " " . pos . " " . a:appendedText . "\<cr>")
endfunction

function! s:SendGDBCommand(termBuf, command)
  call s:TermSendKeys(a:termBuf, a:command."\<cr>")
endfunction

command! -nargs=* Break call s:BreakGDB(<q-args>)
function! s:BreakGDB(appendedText)
  let termBuf = s:GetTermBufNr()
  if termBuf > 0
    call s:SendGDBLineCommand(termBuf, "break", a:appendedText)
    call s:SendGDBCommand(termBuf, "ListOnBreak")
  endif
endfunction

command! -nargs=* Tbreak call s:TbreakGDB(<q-args>)
function! s:TbreakGDB(appendedText)
  let termBuf = s:GetTermBufNr()
  if termBuf > 0
    call s:SendGDBLineCommand(termBuf, "tbreak", a:appendedText)
    call s:SendGDBCommand(termBuf, "ListOnBreak")
  endif
endfunction

command! -nargs=0 Until call s:UntilGDB()
function! s:UntilGDB()
  let termBuf = s:GetTermBufNr()
  if termBuf > 0
    call s:SendGDBCommand(termBuf, "u")
  endif
endfunction

command! -nargs=0 Continue call s:Continue()
function! s:Continue()
  let termBuf = s:GetTermBufNr()
  if termBuf > 0
    call s:SendGDBCommand(termBuf, "continue")
  endif
endfunction

command! -nargs=0 Pause call s:Pause()
function! s:Pause()
  let termBuf = s:GetTermBufNr()
  if termBuf > 0
    call s:SendGDBCommand(termBuf, "\<c-c>")
  endif
endfunction

command! -nargs=* -complete=tag Evaluate call s:Evaluate(<q-args>)
function! s:Evaluate(...)
  let termBuf = s:GetTermBufNr()
  let eval_expression = a:1
  if (len(eval_expression) == 0)
    let eval_expression = expand('<cexpr>')
  endif
  if termBuf > 0
    call s:SendGDBCommand(termBuf, 'p ' . eval_expression)
  endif
endfunction

let s:guiFontSize = 8
command! -nargs=0 GuiFontIncrease call s:GuiFont('+')
command! -nargs=0 GuiFontDecrease call s:GuiFont('-')
command! -nargs=0 GuiFontDefault call s:GuiFont('=')
function! s:GuiFont(command)
  if a:command == '+'
    let s:guiFontSize += 1
  elseif a:command == '-'
    let s:guiFontSize -= 1
  elseif a:command == '='
    let s:guiFontSize = 8
  endif
  if has('win32')
    execute('silent! set guifont=Consolas:h'.s:guiFontSize)
  else
    execute('silent! set guifont=Inconsolata\ Medium\ '.s:guiFontSize.',\ Monospace\ '.s:guiFontSize)
  endif
endfunction
"""""""""""""""""""""""""""""""""""""""""""""""""""""
"Custom Netrw Functions
"""""""""""""""""""""""""""""""""""""""""""""""""""""
function! SetLocalDir(islocal)
  " b:netrw_curdir rather than %:p:h. Netrw frequently reuses an unnamed buffer for a
  " directory listing, and %:p:h then expands to the current directory instead of the
  " one on screen, so the lcd silently does nothing. netrw#UserMaps guarantees
  " b:netrw_curdir is set before it calls this.
  return 'lcd ' . fnameescape(b:netrw_curdir) . '|pwd'
endfunction
let g:Netrw_UserMaps=[["l","SetLocalDir"]]

function! AdjustPath()
 " Get the current file's directory
 let l:current_file_dir = expand('%:p:h')

 " Get the current working directory
 let l:current_working_dir = getcwd()

 " Check if the current file's directory is a subdirectory of the current working directory
 if l:current_file_dir =~ '^' . escape(l:current_working_dir, '\') . '/'
   " Set path to prioritize the current file's directory
   setlocal path=.,**
 else
   " Otherwise use the current working directory and then fall back to
   " the current file's directory.
   setlocal path=**,.
 endif
endfunction
"""""""""""""""""""""""""""""""""""""""""""""""""""""
"Auto Functions
"""""""""""""""""""""""""""""""""""""""""""""""""""""
let s:ftToNotSetHidden = ['netrw']
augroup vimrc
  autocmd! vimrc
  au VimEnter * call s:SetupPlugins()
  au BufNewFile,BufRead,BufEnter *.s43,*.S43 set ft=msp | set shiftwidth=2 | set tabstop=2 |set softtabstop=2
  au BufNewFile,BufRead *.au3 set ft=autoit
  au BufNewFile,BufRead *.gdb set ft=gdb
  au BufNewFile,BufRead Makefile* set ft=make
  au BufNewFile,BufRead *.make set ft=make
  au BufNewFile,BufRead *.mk set ft=make
  au BufNewFile,BufRead *.md setlocal textwidth=80
  au BufNewFile,BufRead,BufEnter *.zig set shiftwidth=4 | set tabstop=4 |set softtabstop=4
  " Don't scan include files
  au BufEnter * set complete-=i
  au BufEnter * set complete-=u
  au WinNew * let &list = s:list_tracker
  au WinLeave * let s:list_tracker = &list
  "turn off cursorline when diffing
  au BufEnter,BufNew * if &diff | set nocursorline | endif
  au BufNewFile,BufRead *.xaml set ft=xml
  au FileType make setlocal noexpandtab
  "netrw keeps setting nohidden!
  autocmd BufEnter * if index(s:ftToNotSetHidden, &ft) < 0 | set hidden
  autocmd BufEnter,DirChanged * call AdjustPath()
  " A colorscheme clears User9, and in neovim it also reassigns the terminal palette
  autocmd ColorScheme * call s:StatusLineColor() | call s:ApplyTerminalColors()
augroup END

set background=light
silent! colorscheme onedark
call s:StatusLineColor()
call s:ApplyTerminalColors()

call s:GuiFont('=')

let g:netrw_banner = 0

" cause bashrc to be loaded when running shell commands in vim
" Also applies to make command for example
let $BASH_ENV = "~/.bashrc"

" Auto install vim-plug and then set it up. globpath() rather than a fixed path so
" neovim, whose runtimepath already includes ~/.vim, does not download a second copy.
let s:data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(globpath(&runtimepath, 'autoload/plug.vim'))
  silent execute '!curl -fLo '.s:data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Source the mylint plugin file. resolve() because neovim reaches this file through
" a symlinked init.vim, where <sfile> is ~/.config/nvim/init.vim.
execute 'source' fnamemodify(resolve(expand('<sfile>')), ':p:h') . '/mylint.vim'

call plug#begin('~/.vim/plugged')
   Plug 'godlygeek/tabular'
   Plug 'preservim/vim-markdown'
   let g:vim_markdown_no_default_key_mappings = 1
   let g:vim_markdown_fenced_languages = ['c++=cpp', 'viml=vim', 'bash=sh', 'ini=dosini', 'c', 'python']
   Plug 'ziglang/zig.vim'
   Plug 'skywind3000/asyncrun.vim'
   " mylint.vim calls async#job#start so the one file runs under vim and neovim
   Plug 'prabirshrestha/async.vim'
   Plug 'peterhoeg/vim-qml'
   Plug 'artoj/qmake-syntax-vim'

   Plug 'rickhowe/diffchar.vim'
   Plug 'rickhowe/spotdiff.vim'
   Plug 'rickhowe/diffunitsyntax'
call plug#end()
